version: 0.0
os: linux
files:
  - source: /ocr-races-0.0.1-SNAPSHOT.jar
    destination: /var/lib/tomcat8/webapps
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

